export const CONFIG_OAUTH = 'CONFIG_OAUTH';
export const CONFIG_JWT_ACCESS = 'CONFIG_JWT_ACCESS';
export const CONFIG_JWT_REFRESH = 'CONFIG_JWT_REFRESH';
export const CONFIG_JWT_ADMIN = 'CONFIG_JWT_ADMIN';
